name = "Ефим"
age = "31"
appearance = "Худой жилистый мужчина среднего роста, тёмно-русые волосы до плеч, стянутые полоской кожи, короткая неровная борода. Тёмные глаза, обмороженный кончик носа, белый шрам через левую бровь. Толстый овчинный полушубок мехом внутрь, поверх — холщовая накидка цвета мокрого камня, на голове вязаная шапка с наушниками. Через плечо холщовая сумка о двух отделениях с бурой сургучной печатью, на поясе плоский фонарь на сале. Ноги обмотаны сукном поверх сапог."
dirty = true
