"""What ONE line's voice is heard through: the band it came down, the room it was in,
the machine carrying it — and whatever is running in the background behind it.

This is `filters.py` for sound, and the two are deliberately not the same shape. A
montage look is a property of the WHOLE video, because half of those effects are a
story about the thing the video is supposedly playing on and a tube that appears for
one shot is a transition rather than a tube. A voice filter is the opposite: it is a
property of ONE LINE, because what it says is who is speaking and from where. A radio
dispatcher, a recording played back in the room, a line remembered rather than heard —
each of those is one line among forty that are not, and a filter that covered the
whole video could not say any of it.

**Nothing here is allowed to change the LENGTH of a take.** The video filters may not
change the frame size; this is the same rule one clock further in, and it is stricter
than it looks. A line's length is the pipeline's timeline: the word timings are
measured against it, the picture is cut on those words, the subtitles are burned from
them, and in a drama the clip was sized to it. So every chain below is written to come
out the length it went in — a pitch shift is `asetrate` undone by exactly the inverse
`atempo`, never `atempo` alone — and the one place that is not enough, a reverb tail
that outlives the line, is cut by the `apad`/`atrim` pair :func:`plan` ends with. That
cut lands in the silence after the last word, which is why `hall` at full dose is a big
room and not a clipped one.

**The filter is never baked into the voice.** The synthesizer's take is kept beside
the filtered one (`scene_03.dry.mp3` next to `scene_03.mp3` — see
`pipeline.stages.tts.dry_path`), and the filtered take is always DERIVED from it. That
is the whole reason this module exists as a card and not as a prompt: switching a
line from `плёнка` to `рация`, or taking the filter off, costs one ffmpeg pass over
one line and no synthesis at all. On a cloning engine that difference is not
performance, it is identity — generation is sampled, so re-voicing would hand back
another reading of the line, and the take the operator listened to and approved would
be gone.

**A background sound is part of a filter, not a second feature.** Half of what makes
a voice sound like 1961 is not the voice: it is the projector two metres behind the
microphone. So a card carries a BED — a loop that plays under the line for exactly as
long as the line lasts — and the beds below are generated by ffmpeg out of nothing
(:data:`BEDS`), so the shipped cards need no audio files committed beside them. A card
may name a file instead, and that is how a bought loop or a recording of a real room
gets in.

**A bed belongs to a RUN of lines, not to one line.** The filter is chosen per line,
but a projector does not stop and start again between two sentences, and that is
exactly what a bed built per line sounded like — a dip at every boundary, loudest on
the steady backgrounds where there is nothing else to hide it. So consecutive lines
carrying the same card are one stretch: each is built with `at`, how far into the run
it starts, and the fades are spent at the two ENDS of the run rather than at every
seam inside it (see :func:`plan`). What `at` buys depends on the bed — a projector and
a mains hum have a phase and are wound forward to it (:func:`_clock`), hiss and room
tone have none and are given a different draw instead (:func:`_seed`), because
`anoisesrc` is deterministic and two lines of it would otherwise be the same noise
sample for sample. A bed that is a FILE is seeked into, so a run reads the loop
straight through.

The one place a run is still interrupted is a PAUSE inside it: a pause has no take to
put a bed on, so the background is absent for its length and picks up afterwards where
it would have been. A gap, not a restart — and it is the restart the ear objects to.

Each effect is a dose, 0-100, exactly as in the montage look: 20 is a suggestion and
100 is the joke. They stack, and they always stack in CATALOGUE order rather than the
order they were switched on, because that order is the signal path — what the voice IS,
then what it came through, then the room it was in, then the medium carrying it, then
the transport breaking up. A room added before a telephone band is a room heard over
the telephone; the other way round it is a telephone heard in a room, and those are
two different places to be standing.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from typing import Callable

# What every chain below is written against, and what :func:`plan` resamples to before
# the first filter runs. It has to be a constant rather than whatever the take happens
# to be: `asetrate` is the only way to shift pitch without a library, and it is a
# multiple of the rate the samples are read at.
RATE = 44100

# How much of a bed is generated BEFORE the part that is kept, on a line that continues
# a run (see :func:`_bed`). A quarter of a second is far more than any filter here needs
# to settle — the slowest is a 700 Hz lowpass — and it costs a quarter second of
# expression evaluation on a line that is already being re-encoded.
PREROLL = 0.25

# One statement of a filtergraph, e.g. "[0:a]highpass=f=300[vout]".
Statement = str
# dose 0..1 -> one audio filterchain, commas and all
Build = Callable[[float], str]


def _lerp(lo: float, hi: float, d: float) -> float:
    """Where a dose lands between "barely there" (1) and "the whole joke" (100)."""
    return lo + (hi - lo) * d


@dataclass(frozen=True)
class Effect:
    key: str
    note: str  # one line of English for the API; the interfaces have their own labels
    build: Build


# --- what the voice IS ----------------------------------------------------
#
# A pitch shift and nothing else. Both of these are `asetrate` — read the samples at
# another rate, which moves the pitch and the length together — followed by exactly
# the inverse `atempo`, which puts the length back and leaves the pitch where it went.
# Measured: a 7.272s take comes back 7.271995s at every dose, which is the file format
# rounding and not the filter.


def _deep(d: float) -> str:
    # down to 0.78 at full dose: a bigger chest, not a monster. Past about 0.7 the
    # formants go with it and it stops being a person.
    r = _lerp(1.0, 0.78, d)
    return f"asetrate={RATE}*{r:.4f},aresample={RATE},atempo={1 / r:.4f}"


def _thin(d: float) -> str:
    r = _lerp(1.0, 1.30, d)
    return f"asetrate={RATE}*{r:.4f},aresample={RATE},atempo={1 / r:.4f}"


def _nasal(d: float) -> str:
    # pinched: a peak where the nose resonates, and the chest and the sibilance taken
    # out from under it. Three peaking filters rather than a band, because the point is
    # the BUMP at 1k — a band would only make it quieter and narrower.
    return (
        f"equalizer=f=1000:w=700:t=h:g={_lerp(0, 9, d):.2f},"
        f"equalizer=f=350:w=320:t=h:g={_lerp(0, -7, d):.2f},"
        f"equalizer=f=2800:w=1000:t=h:g={_lerp(0, -4, d):.2f}"
    )


# --- what it came through -------------------------------------------------
#
# All four of these throw away most of the spectrum, and all four therefore carry a
# makeup gain. That gain is not cosmetic: the delivery pass levels the finished track
# as ONE thing (`ffmpeg._delivery_cmd` runs `loudnorm` over the whole voice), so a
# filtered line that came out 6 LU quieter than its neighbours stays 6 LU quieter in
# the cut — and the operator would be left guessing which of their fourteen sliders did
# it. So every chain in this module was measured against the same voiced line at doses
# 1, 50 and 100 and tuned until the filtered take lands within about two units of the
# dry one, which is the band inside which nobody reaches for the volume. The makeup on
# the two compressed bands rises as the dose to the power of 1.6 rather than along a
# straight line, because the squashing arrives before the band narrows: a linear
# makeup is correct at the top of the slider and 3 LU too loud in the middle of it.
#
# `VoiceFxConfig.level` is the per-card remainder of this, and it is the operator's
# rather than a correction of the above: a quiet voice through a telephone needs a
# different number than a loud one, and no makeup inside a chain can know which it has.


def _phone(d: float) -> str:
    # The telephone band proper: 300-3400, the presence peak the earpiece adds, and
    # the squash a line with automatic gain on it has.
    return (
        f"highpass=f={_lerp(90, 320, d):.0f}:p=2,"
        f"lowpass=f={_lerp(12000, 3200, d):.0f}:p=2,"
        f"equalizer=f=1800:w=1400:t=h:g={_lerp(0, 5, d):.2f},"
        f"acompressor=threshold={_lerp(0.30, 0.06, d):.3f}:ratio={_lerp(2, 6, d):.1f}"
        f":attack=6:release=120:makeup={1.0 + 1.3 * d ** 1.6:.2f}"
    )


def _radio(d: float) -> str:
    # Short wave: a wider band than a telephone but a much harder limiter, and the
    # first hint of the signal being digitised badly. The HISS that finishes the
    # impression is not here — it is a bed (see :data:`BEDS`), because it is a sound in
    # the room rather than something done to the voice, and because then its level is
    # one number the operator can turn down.
    return (
        f"highpass=f={_lerp(80, 200, d):.0f},"
        f"lowpass=f={_lerp(14000, 4200, d):.0f},"
        f"acompressor=threshold={_lerp(0.25, 0.05, d):.3f}:ratio={_lerp(3, 9, d):.1f}"
        f":attack=4:release=90:makeup={1.0 + 1.7 * d ** 1.6:.2f},"
        f"acrusher=bits={_lerp(16, 10, d):.1f}:mix={_lerp(0, 0.25, d):.2f}:mode=log"
    )


def _megaphone(d: float) -> str:
    # A loudhailer: no bottom at all, a hard horn peak, driven into saturation, and the
    # one short reflection that says the sound crossed a square to reach you.
    #
    # Driven by the gain in FRONT of the clipper and brought back by its own `output`,
    # rather than by lowering `threshold`: that option caps the waveform AT the
    # threshold, so a dose of it was a dose of attenuation — measured, the horn at full
    # dose came out 13 LU under the dry line. `tanh` and not `atan` for the same kind of
    # reason: ffmpeg normalises the atan curve by `atan(1)`, which costs 4 LU on its own
    # at unity gain, where tanh costs 0.2.
    drive = _lerp(1.0, 3.2, d)
    return (
        f"highpass=f={_lerp(120, 520, d):.0f}:p=2,"
        f"lowpass=f={_lerp(12000, 3600, d):.0f}:p=2,"
        f"equalizer=f=2200:w=1500:t=h:g={_lerp(0, 8, d):.2f},"
        f"volume={drive:.3f},"
        f"asoftclip=type=tanh:output={drive ** -0.75:.3f},"
        f"aecho=1:{_lerp(1.0, 0.90, d):.3f}:24:{_lerp(0.0, 0.30, d):.3f},"
        f"volume={_lerp(1.0, 1.7, d):.2f}"
    )


def _muffled(d: float) -> str:
    # Through a door, a wall, a pillow: the top gone and the bottom left standing.
    return (
        f"lowpass=f={_lerp(9000, 700, d):.0f}:p=2,"
        f"equalizer=f=200:w=220:t=h:g={_lerp(0, 4, d):.2f},"
        f"volume={_lerp(1.0, 1.1, d):.2f}"
    )


# --- the room it was in ---------------------------------------------------
#
# `aecho` and not a convolution, because there is no impulse response to ship and
# nothing here wants to be a real hall — it wants to say "this was said in a space".
# The taps are deliberately not multiples of each other: equal spacing is a flutter
# echo, which is a corridor, and a corridor is a different place than either of these.
#
# Both gains are dosed along with the decays, and `in_gain` starts at 1. `aecho`
# multiplies everything it outputs by `out_gain`, so the usual `0.9:0.85` form is an
# unconditional 2.3 LU of attenuation that a dose of zero would not have removed —
# which is not what a slider at its bottom end should do.


def _room(d: float) -> str:
    return (f"aecho=1:{_lerp(1.0, 0.88, d):.3f}:17|29|41:"
            f"{_lerp(0.02, 0.26, d):.3f}|{_lerp(0.01, 0.17, d):.3f}|{_lerp(0.01, 0.11, d):.3f}")


def _hall(d: float) -> str:
    return (f"aecho=1:{_lerp(1.0, 0.88, d):.3f}:97|163|251|367:"
            f"{_lerp(0.02, 0.42, d):.3f}|{_lerp(0.02, 0.30, d):.3f}"
            f"|{_lerp(0.01, 0.21, d):.3f}|{_lerp(0.01, 0.14, d):.3f}")


# --- the medium carrying it -----------------------------------------------


def _lofi(d: float) -> str:
    # Bits AND samples: the first is the quantisation hash, the second is the
    # sample-and-hold that makes it sound like it came off a machine with a clock
    # rather than off a bad microphone. Anti-aliasing comes off as the dose goes up,
    # because the aliasing is the sound.
    return (
        f"acrusher=bits={_lerp(16, 5, d):.1f}:samples={_lerp(1, 10, d):.1f}"
        f":mix={_lerp(0.30, 1.0, d):.2f}:mode=log:aa={_lerp(0.5, 0.0, d):.2f},"
        f"volume={_lerp(1.0, 1.15, d):.2f}"
    )


def _wobble(d: float) -> str:
    # Worn transport: the speed wandering and the level wandering with it, on two
    # rates that do not divide into each other so the two never beat together into
    # one obvious oscillation. This is the half of "old film" that no amount of
    # equalisation gives you.
    return (
        f"vibrato=f={_lerp(2.5, 6.5, d):.2f}:d={_lerp(0.03, 0.32, d):.3f},"
        f"tremolo=f={_lerp(3.1, 8.3, d):.2f}:d={_lerp(0.02, 0.22, d):.3f}"
    )


# --- the transport breaking up --------------------------------------------


def _crush(d: float) -> str:
    # Overdriven: pushed into the saturator and brought back down by its own output
    # gain, so a dose changes how hard it is driven and not how loud the result is. The
    # compensation is the drive to the power of -3/4 rather than its reciprocal,
    # because a saturated signal is louder than its peak suggests — measured across the
    # range, that exponent holds a filtered line within 2 LU of the dry one and the
    # reciprocal leaves it 4 too quiet.
    drive = _lerp(1.0, 4.5, d)
    return (
        f"volume={drive:.3f},"
        f"asoftclip=type=tanh:output={drive ** -0.75:.3f},"
        f"alimiter=limit=0.95:level=disabled"
    )


def _dropout(d: float) -> str:
    """The signal cutting out — twice over, on two clocks, so the gaps land apart,
    together, apart again instead of pulsing on one beat.

    `enable` bypasses the filter outright on the frames where it is not firing, so the
    bill is paid only while something is actually broken — the same arrangement the
    montage glitch uses. A dose is BOTH how often a gap comes and how long it lasts: at
    10 the line stumbles once, at 100 it is barely getting through.
    """
    period = _lerp(11.0, 2.2, d)
    burst = _lerp(0.04, 0.26, d)
    return (
        f"volume=volume=0:enable='lt(mod(t,{period:.2f}),{burst:.3f})',"
        f"volume=volume={_lerp(1.0, 0.25, d):.2f}"
        f":enable='lt(mod(t+1.7,{period * 0.41:.2f}),{burst * 0.6:.3f})'"
    )


# Order is the signal path, not the menu: what the voice is, what it came through, the
# room, the medium, the transport (see the module docstring). Every interface lists
# them in this order too, so what the operator reads top to bottom is what the voice
# goes through.
CATALOGUE: list[Effect] = [
    Effect("deep", "pitch it down — a bigger chest, same length", _deep),
    Effect("thin", "pitch it up — smaller, younger, a toy", _thin),
    Effect("nasal", "pinched through the nose", _nasal),
    Effect("phone", "the telephone band: 300-3400, squashed", _phone),
    Effect("radio", "short wave: limited hard, starting to come apart", _radio),
    Effect("megaphone", "a loudhailer across a square: no bottom, clipped, one reflection", _megaphone),
    Effect("muffled", "through a door: the top gone, the bottom left", _muffled),
    Effect("room", "said in a small room", _room),
    Effect("hall", "said in a big one", _hall),
    Effect("lofi", "off a machine with a bad clock: bits and sample-and-hold", _lofi),
    Effect("wobble", "worn transport: the speed and the level wandering", _wobble),
    Effect("crush", "driven into the clipper", _crush),
    Effect("dropout", "the signal cutting out in bursts", _dropout),
]

KEYS: list[str] = [e.key for e in CATALOGUE]
BY_KEY: dict[str, Effect] = {e.key: e for e in CATALOGUE}


# --- what is running behind the voice -------------------------------------
#
# Every bed here is generated by ffmpeg out of an expression, which is the whole point:
# the shipped cards are the documentation of what a voice filter IS, and documentation
# that needs a megabyte of audio committed beside it does not get read. A card that
# wants a real recording names a FILE instead (`VoiceFxConfig.bed_file`), and that is
# the road for a bought loop or a room somebody actually stood in.
#
# `random(n)` in an ffmpeg expression is evaluated per sample and returns 0..1, which
# is where the noise in all of these comes from; `n` is an index into ffmpeg's own
# generator state, so two terms of one expression asking for `random(0)` and
# `random(1)` are two independent streams rather than the same number twice.
#
# Every bed is built for a position in its RUN rather than for a line (`at`, see
# :func:`plan`), which is what lets one bed carry across a line boundary instead of
# starting again. The two ways of using that number are both here, because which one a
# bed needs is a fact about the bed: a projector and a mains hum have a PHASE and want
# the clock moved; hiss and room tone have none and want a different draw of the dice,
# since `anoisesrc` is deterministic and two lines of it would otherwise be the same
# noise sample for sample.


def _clock(at: float) -> str:
    """What a bed's expression uses instead of `t`: its own time, shifted to where in
    the run this piece sits. Exactly `t` at the head of a run, so the ordinary case
    produces the expression it always did."""
    return "t" if abs(at) < 0.0005 else f"(t+{at:.3f})"


def _seed(at: float) -> int:
    """A generator seed that differs along a run, so a deterministic noise source does
    not hand two consecutive lines the identical sample. Derived from the position
    rather than rolled, so a take re-rendered for any other reason comes back the same
    — a bed that changed every time it was laid would make every stamp comparison a
    lie (see :func:`stamp`)."""
    return int(abs(at) * 1000) % 2147483647


@dataclass(frozen=True)
class Bed:
    key: str
    note: str
    # (seconds, clock) -> a lavfi source chain producing the loop, unlabelled.
    #
    # Bounded by the length it is asked for rather than left infinite: a source with no
    # duration in a filtergraph is a command that has to be stopped from outside, and
    # `-shortest` answering for a file that is still being written is the kind of race
    # that shows up once in fifty runs.
    #
    # `at` is how far into its RUN this piece of the bed starts, and it is the whole of
    # how a bed survives a line boundary (see :func:`plan`). A line two seconds into a
    # run of the same card builds its expression against `(t+2.000)`, so its projector
    # is on the frame the previous line's projector was about to reach rather than back
    # at the first clack. Each builder derives what it needs from it — :func:`_clock`
    # for the ones with a phase, :func:`_seed` for the ones that are only noise —
    # rather than being handed a finished substitution, because `t` occurs inside words
    # (`exp`, `atempo`, `vibrato`) and a blind replacement would corrupt a filter name
    # one day.
    build: Callable[[float, float], str]


def _bed_projector(seconds: float, at: float) -> str:
    """A 16mm projector two metres behind the microphone.

    Four things at once, and the clatter is the one that matters: a very short noise
    burst fired 24 times a second — `mod(t*24,1)` is where we are inside one frame's
    worth of time, so dividing it by 24 turns that back into seconds and `exp` decays
    over 3 ms, which is a clack rather than a tick. The softer burst half a frame
    behind it is the sprocket pulling the next frame down; the two sines are the motor;
    the last term is the air in the room.
    """
    t = _clock(at)
    return (
        f"aevalsrc=exprs='0.50*(random(0)*2-1)*exp(-320*mod({t}*24,1)/24)"
        f"+0.20*(random(1)*2-1)*exp(-90*mod({t}*24+0.5,1)/24)"
        f"+0.10*sin(2*PI*48*{t})+0.05*sin(2*PI*96*{t})"
        f"+0.03*(random(2)*2-1)':s={RATE}:c=mono:d={seconds:.3f},"
        "lowpass=f=5200,highpass=f=70"
    )


def _bed_hiss(seconds: float, at: float) -> str:
    # Tape, or an open channel: pink rather than white, because white noise is a
    # hardware fault and pink is a medium.
    #
    # Noise has no phase to carry across a line boundary, so the clock buys nothing
    # here — what it buys is a different SEQUENCE: `anoisesrc` is deterministic, so two
    # consecutive lines would otherwise hiss the identical sample for sample. Which is
    # inaudible as hiss and very audible as crackle, hence the same treatment for both.
    return (f"anoisesrc=c=pink:a=0.30:r={RATE}:d={seconds:.3f}:seed={_seed(at)},"
            "highpass=f=300,lowpass=f=9000")


def _bed_hum(seconds: float, at: float) -> str:
    # Mains, and its first two harmonics — 50 Hz because that is what the rooms this
    # is pretending to be recorded in ran on. The one bed where the clock is doing its
    # literal job: a 50 Hz tone restarted mid-sentence is a click, and continued is
    # nothing at all.
    t = _clock(at)
    return (f"aevalsrc=exprs='0.50*sin(2*PI*50*{t})+0.22*sin(2*PI*100*{t})"
            f"+0.09*sin(2*PI*150*{t})':s={RATE}:c=mono:d={seconds:.3f},lowpass=f=900")


def _bed_crackle(seconds: float, at: float) -> str:
    # A needle in a groove: sparse impulses instead of a continuous noise floor. The
    # gate is `gt(random(0),0.9984)`, so about seventy clicks a second get through, each
    # one sample long before the filters below smear it into a tick.
    #
    # `random()` does not read the clock, so the offset cannot decorrelate this one the
    # way it does the projector — two lines would tick identically, which on sparse
    # impulses reads as a loop rather than as a groove. So the gate is tilted by a
    # vanishing function of the clock instead: it changes which samples pass without
    # changing how many.
    t = _clock(at)
    return (f"aevalsrc=exprs='gt(random(0),0.9984+0.0015*sin({t}*7919))*(random(1)*2-1)"
            f"+0.04*(random(2)*2-1)':s={RATE}:c=mono:d={seconds:.3f},"
            "highpass=f=1200,lowpass=f=9000")


def _bed_rain(seconds: float, at: float) -> str:
    # Weather outside the window: a wide noise with the top rolled off, breathing
    # slowly so it does not sit still the way a noise generator does. The breathing is
    # a `tremolo`, which has a phase of its own and so reads the clock like the tonal
    # beds do; the noise under it only needs a seed.
    t = _clock(at)
    return (f"anoisesrc=c=white:a=0.30:r={RATE}:d={seconds:.3f}:seed={_seed(at)},"
            "highpass=f=400,lowpass=f=6500,tremolo=f=0.21:d=0.22")


def _bed_roomtone(seconds: float, at: float) -> str:
    # The sound of a room with nothing happening in it, which is never silence. Brown
    # noise under 700 Hz is exactly what a microphone in an empty room records.
    return (f"anoisesrc=c=brown:a=0.35:r={RATE}:d={seconds:.3f}:seed={_seed(at)},"
            "lowpass=f=700")


BEDS: list[Bed] = [
    Bed("projector", "a film projector running behind the microphone", _bed_projector),
    Bed("hiss", "tape hiss, or an open channel", _bed_hiss),
    Bed("hum", "mains hum at 50 Hz", _bed_hum),
    Bed("crackle", "a needle in a groove", _bed_crackle),
    Bed("rain", "rain outside the window", _bed_rain),
    Bed("roomtone", "an empty room, which is never silent", _bed_roomtone),
]

BED_KEYS: list[str] = [b.key for b in BEDS]
BED_BY_KEY: dict[str, Bed] = {b.key: b for b in BEDS}


# --- reading a card -------------------------------------------------------


def normalise(spec: dict | None) -> dict[str, int]:
    """Only the effects that exist, only the doses that mean anything: unknown keys are
    dropped and everything else is clamped into 1..100 (0 IS "off", so it goes too).

    Cards are hand-editable TOML, and a line must not fail in ffmpeg over a typo — it
    is simply heard without that effect. Same tolerance, for the same reason, as
    `filters.normalise`.
    """
    out: dict[str, int] = {}
    for key in KEYS:  # catalogue order, so the stored dict reads like the signal path
        if not spec or key not in spec:
            continue
        try:
            dose = int(round(float(spec[key])))
        except (TypeError, ValueError):
            continue
        if dose > 0:
            out[key] = min(100, dose)
    return out


def describe(spec: dict | None) -> str:
    """`{"phone": 60, "radio": 20}` -> "phone 60, radio 20", in catalogue order."""
    return ", ".join(f"{k} {v}" for k, v in normalise(spec).items())


def chain(spec: dict | None, level: float = 1.0) -> str:
    """Everything the card does TO THE VOICE, as one filterchain — or "" for a card
    that only puts something behind it.

    `level` is the card's own output gain, applied last. It exists because these
    chains throw spectrum away and no makeup gain is right for every voice: a card
    that still comes out quiet next to its neighbours is fixed with one number rather
    than by re-tuning the effects.
    """
    active = normalise(spec)
    parts = [BY_KEY[key].build(active[key] / 100.0) for key in active]
    if abs(float(level) - 1.0) > 0.005:
        parts.append(f"volume={max(float(level), 0.0):.3f}")
    return ",".join(p for p in parts if p)


def _bed(card, seconds: float, at: float, opens: bool, closes: bool) -> tuple[list[str], str]:
    """`(extra ffmpeg inputs, the chain that produces the bed)` for one card.

    Two shapes behind one answer. A generated bed is a SOURCE and lives inside the
    filtergraph, which is why most cards open no second input at all. A bed that is a
    file has to be read, and is read on a loop (`-stream_loop -1`) because a loop
    shorter than the line would otherwise simply stop halfway through it — and seeked
    into, so a run of lines reads the file straight through instead of restarting it.

    `at`, `opens` and `closes` are this line's place in its RUN (see :func:`plan`), and
    they are the whole of what makes several lines carrying one card sound like one
    stretch rather than several: the generator is wound forward to where the previous
    line left it, and the fades happen at the two ends of the run instead of at every
    seam inside it.

    `("", [])` for a card with no bed, a bed naming a generator that does not exist,
    and a bed naming a file that is not there. The last one is the same tolerance
    `normalise` has: a card whose loop was moved is heard without it, rather than
    taking the line's whole synthesis down with it.
    """
    gain = max(float(card.volume), 0.0)
    shape = f"aresample={RATE},aformat=channel_layouts=stereo,volume={gain:.3f}"
    fade = max(float(card.fade), 0.0)
    if fade > 0.005 and seconds > 2.2 * fade:
        # Only where the run actually begins and ends. A fade at every line boundary is
        # exactly the dip that makes a continuous background sound like it is being
        # switched on and off — which is what this used to do, and what it is for.
        if opens:
            shape += f",afade=t=in:d={fade:.3f}"
        if closes:
            shape += f",afade=t=out:st={seconds - fade:.3f}:d={fade:.3f}"
    path = card.bed_file
    if path is not None:
        if not path.is_file():
            return [], ""
        # `-ss` before `-i` on a looped input seeks into the first pass and then loops
        # from the top, which is what "carry on from where the last line left it" means
        # for a file. The modulo keeps the seek inside the file on a long run; a loop
        # whose length cannot be read is simply played from the start.
        args = ["-stream_loop", "-1"]
        if at > 0.005:
            args += ["-ss", f"{at % max(_bed_seconds(path), 0.001):.3f}"]
        return args + ["-i", str(path)], f"[1:a]{shape}"
    made = BED_BY_KEY.get((card.bed or "").strip().lower())
    if made is None:
        return [], ""
    # A line that continues a run is generated with a run-up and then trimmed back to
    # where it was asked to start. Every bed's shaping ends in a lowpass or a highpass,
    # and an IIR filter started from zero state rings for a few milliseconds before it
    # settles — which lands exactly on the seam and is heard as the tick this whole
    # arrangement exists to remove. Measured on the mains hum: the jump between two
    # samples at the join was twelve times the biggest jump anywhere else in the file,
    # identical whether the bed was restarted or wound forward, because it was never the
    # phase — it was the filter waking up. The head of a run needs none of this: its
    # transient is under the fade-in.
    pre = 0.0 if at <= 0.005 else PREROLL
    chain = made.build(seconds + pre, max(at - pre, 0.0))
    if pre:
        chain += f",atrim=start={pre:.3f},asetpts=N/SR/TB"
    return [], f"{chain},{shape}"


# How long a bed FILE is, remembered against the file rather than its name. Asked once
# per card per process and answered by a subprocess, which is fine once and ruinous in
# a loop: a run of forty lines on one card would otherwise be forty `ffprobe`s to work
# out the same number. Keyed the way `ffmpeg.video_dims` keys its own cache, so a loop
# replaced under the same name is measured again.
_BED_SECONDS: dict[tuple, float] = {}


def _bed_seconds(path) -> float:
    try:
        st = path.stat()
    except OSError:
        return 0.0
    key = (str(path), st.st_size, st.st_mtime_ns)
    if key not in _BED_SECONDS:
        from .ffmpeg import duration_of  # local: this module is imported by the catalogues

        try:
            _BED_SECONDS[key] = max(duration_of(path), 0.0)
        except Exception:  # noqa: BLE001 — an unreadable loop is played from the start
            _BED_SECONDS[key] = 0.0
    return _BED_SECONDS[key]


def active(card) -> bool:
    """Whether this card actually does anything to a line.

    Asked before a take is re-rendered, because the honest answer for a card that is
    empty, retired, or whose loop has gone missing is to leave the voice alone — and
    leaving it alone means the file stays the synthesizer's own, not a re-encode of it.
    """
    if card is None or card.retired:
        return False
    if normalise(card.effects):
        return True
    if abs(float(card.level) - 1.0) > 0.005:
        return True
    return bool(_bed(card, 1.0, 0.0, True, True)[1])


def stamp(card) -> str:
    """What a filtered take carries to say WHICH filter is on it: the card's name and a
    fingerprint of everything in it that changes the sound.

    The name alone would not do. A card is edited in place — that is most of what the
    editor is for — and a take stamped only `плёнка` would go on claiming to be
    current after the projector was turned up. The fingerprint is what makes the next
    pass through the voicing stage re-derive exactly the lines whose card has moved
    and no others (see `pipeline.stages.tts._settle_fx`).

    Empty for a card that does nothing, which is the same string a take nothing was
    laid on carries — so "no filter" and "a filter that is a no-op" are one state and
    not two.
    """
    if not active(card):
        return ""
    body = json.dumps({
        "effects": normalise(card.effects),
        "bed": (card.bed or "").strip(),
        "volume": round(float(card.volume), 3),
        "fade": round(float(card.fade), 3),
        "level": round(float(card.level), 3),
    }, sort_keys=True)
    return f"{card.name}:{hashlib.sha1(body.encode()).hexdigest()[:12]}"


def plan(card, seconds: float, at: float = 0.0,
         opens: bool = True, closes: bool = True) -> tuple[list[str], list[Statement]]:
    """The ffmpeg inputs and the filtergraph taking the voice at `[0:a]` to `[out]`.

    The whole of what a card does, in one place, so there is one answer to "what will
    this sound like" and `ffmpeg.voice_fx` is the three lines that run it.

    `at`, `opens` and `closes` say where this line sits in its RUN — the stretch of
    consecutive lines carrying this same card (`pipeline.stages.tts.fx_runs` works them
    out). They matter to the BED and to nothing else, and they are what makes several
    lines in a row sound like one continuous background instead of one that restarts at
    every line: the generator is wound forward to `at`, and the fades are spent at the
    two ends of the run rather than at every boundary inside it. A lone filtered line is
    a run of one, which is the default here and the shape every caller had before runs
    existed.

    What this does NOT reach is a pause in the middle of a run: a pause has no take to
    put a bed on, so the background is genuinely absent for its length and picks up
    afterwards where it would have been. That is a gap, not a restart — the thing the
    ear objects to is the restart.

    It ends in `apad,atrim` every time, including for a card that is only a band-pass.
    That pair is the length invariant made mechanical: pad whatever came out, cut it to
    exactly the length that went in, and no effect anywhere above has to remember that
    it is not allowed to make a take longer. `asetpts` after it, because a trimmed
    stream keeps the timestamps it had and an encoder handed a stream starting at 0.4s
    writes 0.4s of nothing at the front of the file.
    """
    seconds = max(float(seconds), 0.05)
    voice = chain(card.effects, card.level)
    bed_args, bed_chain = _bed(card, seconds, max(float(at), 0.0), opens, closes)
    nodes: list[Statement] = [
        f"[0:a]aresample={RATE},aformat=channel_layouts=stereo"
        + (f",{voice}" if voice else "") + "[vfx]"
    ]
    tag = "[vfx]"
    if bed_chain:
        nodes.append(f"{bed_chain}[bed]")
        # normalize=0: the voice has a level of its own and the bed was turned down to
        # sit under it, and dividing both by the number of inputs would make a line
        # quieter for carrying a background than for not
        nodes.append("[vfx][bed]amix=inputs=2:duration=first:dropout_transition=0"
                     ":normalize=0[mixed]")
        tag = "[mixed]"
    nodes.append(f"{tag}apad,atrim=0:{seconds:.3f},asetpts=N/SR/TB[out]")
    return bed_args, nodes
